name: check
on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: Install prereq
      run: |
        sudo brew install docker tfenv tflint
        
    - name: tf fmt
      run: |
        terraform fmt
    - name: tflint
      run: |
        tflint
    - name: tf validate
      run: |
        terraform validate
   
